package com.teammetallurgy.atum.init;

import com.teammetallurgy.atum.Atum;
import com.teammetallurgy.atum.api.AtumMats;
import com.teammetallurgy.atum.api.God;
import com.teammetallurgy.atum.items.*;
import com.teammetallurgy.atum.items.artifacts.anput.AnputsGroundingItem;
import com.teammetallurgy.atum.items.artifacts.anput.AnputsHungerItem;
import com.teammetallurgy.atum.items.artifacts.anubis.AnubisWrathItem;
import com.teammetallurgy.atum.items.artifacts.atem.*;
import com.teammetallurgy.atum.items.artifacts.geb.GebsMightItem;
import com.teammetallurgy.atum.items.artifacts.geb.GebsToilItem;
import com.teammetallurgy.atum.items.artifacts.geb.GebsUndoingItem;
import com.teammetallurgy.atum.items.artifacts.horus.HorusAscensionItem;
import com.teammetallurgy.atum.items.artifacts.horus.HorusSoaringItem;
import com.teammetallurgy.atum.items.artifacts.isis.IsisDivisionItem;
import com.teammetallurgy.atum.items.artifacts.isis.IsisHealingItem;
import com.teammetallurgy.atum.items.artifacts.montu.MontusBlastItem;
import com.teammetallurgy.atum.items.artifacts.montu.MontusStrikeItem;
import com.teammetallurgy.atum.items.artifacts.nepthys.NepthysBanishingItem;
import com.teammetallurgy.atum.items.artifacts.nepthys.NepthysConsecrationItem;
import com.teammetallurgy.atum.items.artifacts.nepthys.NepthysGuardItem;
import com.teammetallurgy.atum.items.artifacts.nuit.NuitsIreItem;
import com.teammetallurgy.atum.items.artifacts.nuit.NuitsQuarterItem;
import com.teammetallurgy.atum.items.artifacts.nuit.NuitsVanishingItem;
import com.teammetallurgy.atum.items.artifacts.osiris.OsirisBlessingItem;
import com.teammetallurgy.atum.items.artifacts.osiris.OsirisMercyItem;
import com.teammetallurgy.atum.items.artifacts.ptah.PtahsDecadenceItem;
import com.teammetallurgy.atum.items.artifacts.ra.RaArmor;
import com.teammetallurgy.atum.items.artifacts.ra.RasFuryItem;
import com.teammetallurgy.atum.items.artifacts.ra.RasStep;
import com.teammetallurgy.atum.items.artifacts.seth.SethsStingItem;
import com.teammetallurgy.atum.items.artifacts.seth.SethsVenomItem;
import com.teammetallurgy.atum.items.artifacts.shu.ShusBreathItem;
import com.teammetallurgy.atum.items.artifacts.shu.ShusExileItem;
import com.teammetallurgy.atum.items.artifacts.shu.ShusSwiftnessItem;
import com.teammetallurgy.atum.items.artifacts.tefnut.TefnutsCallItem;
import com.teammetallurgy.atum.items.artifacts.tefnut.TefnutsRainItem;
import com.teammetallurgy.atum.items.food.CrunchyScarabItem;
import com.teammetallurgy.atum.items.food.EmmerFlourItem;
import com.teammetallurgy.atum.items.food.FishItem;
import com.teammetallurgy.atum.items.food.QuailEggItem;
import com.teammetallurgy.atum.items.tools.*;
import net.minecraft.inventory.EquipmentSlotType;
import net.minecraft.item.*;
import net.minecraft.potion.EffectInstance;
import net.minecraft.potion.Effects;
import net.minecraftforge.registries.ObjectHolder;

import static com.teammetallurgy.atum.misc.AtumRegistry.*;

@ObjectHolder(value = Atum.MOD_ID)
public class AtumItems {
    public static final Item VILLAGER_SPAWN_EGG = registerItem(new VillagerSpawnEggItem(), "villager_spawn_egg");
    public static final Item PALM_STICK = registerItem(new SimpleItem(), "palm_stick");
    public static final Item DEADWOOD_STICK = registerItem(new SimpleItem(), "deadwood_stick");
    public static final Item DUST_BONE_STICK = registerItem(new SimpleItem(), "dusty_bone_stick");
    public static final Item KHNUMITE = registerItem(new SimpleItem(), "khnumite");
    public static final Item DIRTY_COIN = registerItem(new CoinItem(), "coin_dirty");
    public static final Item GOLD_COIN = registerItem(new CoinItem(), "coin_gold");
    public static final Item NEBU_DROP = registerItem(new SimpleItem(), "nebu_drop");
    public static final Item NEBU_INGOT = registerItem(new SimpleItem(), "nebu_ingot");
    public static final RelicItem IDOL_RELICS = registerRelic(RelicItem.Type.IDOL);
    public static final RelicItem IDOL_NECKLACES = registerRelic(RelicItem.Type.NECKLACE);
    public static final RelicItem IDOL_RINGS = registerRelic(RelicItem.Type.RING);
    public static final RelicItem IDOL_BROOCHES = registerRelic(RelicItem.Type.BROOCH);
    public static final RelicItem IDOL_BRACELETS = registerRelic(RelicItem.Type.BRACELET);
    public static final Item EFREET_HEART = registerItem(new SimpleItem(), "efreet_heart");
    public static final Item SCARAB = registerItem(new ScarabItem(), "scarab");
    public static final Item ANPUT_GODSHARD = registerItem(new GodshardItem(God.ANPUT), "anput_godshard");
    public static final Item ANUBIS_GODSHARD = registerItem(new GodshardItem(God.ANUBIS), "anubis_godshard");
    public static final Item ATEM_GODSHARD = registerItem(new GodshardItem(God.ATEM), "atem_godshard");
    public static final Item GEB_GODSHARD = registerItem(new GodshardItem(God.GEB), "geb_godshard");
    public static final Item HORUS_GODSHARD = registerItem(new GodshardItem(God.HORUS), "horus_godshard");
    public static final Item ISIS_GODSHARD = registerItem(new GodshardItem(God.ISIS), "isis_godshard");
    public static final Item MONTU_GODSHARD = registerItem(new GodshardItem(God.MONTU), "montu_godshard");
    public static final Item NEPTHYS_GODSHARD = registerItem(new GodshardItem(God.NEPTHYS), "nepthys_godshard");
    public static final Item NUIT_GODSHARD = registerItem(new GodshardItem(God.NUIT), "nuit_godshard");
    public static final Item OSIRIS_GODSHARD = registerItem(new GodshardItem(God.OSIRIS), "osiris_godshard");
    public static final Item PTAH_GODSHARD = registerItem(new GodshardItem(God.PTAH), "ptah_godshard");
    public static final Item RA_GODSHARD = registerItem(new GodshardItem(God.RA), "ra_godshard");
    public static final Item SETH_GODSHARD = registerItem(new GodshardItem(God.SETH), "seth_godshard");
    public static final Item SHU_GODSHARD = registerItem(new GodshardItem(God.SHU), "shu_godshard");
    public static final Item TEFNUT_GODSHARD = registerItem(new GodshardItem(God.TEFNUT), "tefnut_godshard");
    public static final Item IDOL_OF_LABOR = registerItem(new IdolOfLaborItem(), "idol_of_labor");
    public static final BaseBowItem SHORT_BOW = (BaseBowItem) registerItem(new BaseBowItem(new Item.Properties().maxDamage(384)), "short_bow");
    public static final Item LIMESTONE_SHOVEL = registerItem(new ShovelItem(AtumMats.LIMESTONE, 1.2F, -3.0F, new Item.Properties().group(Atum.GROUP)), "limestone_shovel");
    public static final Item LIMESTONE_PICKAXE = registerItem(new PickaxeItem(AtumMats.LIMESTONE, 1, -2.8F, new Item.Properties().group(Atum.GROUP)), "limestone_pickaxe");
    public static final Item LIMESTONE_AXE = registerItem(new AxeItem(AtumMats.LIMESTONE, 7.0F, -3.2F, new Item.Properties().group(Atum.GROUP)), "limestone_axe");
    public static final Item LIMESTONE_SWORD = registerItem(new SwordItem(AtumMats.LIMESTONE, 3, -2.4F, new Item.Properties().group(Atum.GROUP)), "limestone_sword");
    public static final Item LIMESTONE_HOE = registerItem(new HoeItem(AtumMats.LIMESTONE, -1, -1.8F, new Item.Properties().group(Atum.GROUP)), "limestone_hoe");
    public static final Item NEBU_HAMMER = registerItem(new NebuHammerItem(), "nebu_hammer");
    public static final Item DAGGER_IRON = registerItem(new DaggerItem(ItemTier.IRON), "iron_dagger");
    public static final Item POISON_DAGGER = registerItem(new PoisonDaggerItem(), "dagger_poison");
    public static final Item SCIMITAR_IRON = registerItem(new SwordItem(ItemTier.IRON, 3, -2.4F, new Item.Properties().group(Atum.GROUP)), "iron_scimitar");
    public static final Item GREATSWORD_IRON = registerItem(new GreatswordItem(ItemTier.IRON), "iron_greatsword");
    public static final Item CLUB_IRON = registerItem(new ClubItem(ItemTier.IRON), "iron_club");
    public static final Item KHOPESH_IRON = registerItem(new KhopeshItem(ItemTier.IRON), "iron_khopesh");
    public static final Item STONEGUARD_SWORD = registerItem(new SwordItem(AtumMats.KHNUMITE, 3, -2.4F, new Item.Properties().group(Atum.GROUP)), "stoneguard_sword");
    public static final Item STONEGUARD_GREATSWORD = registerItem(new GreatswordItem(AtumMats.KHNUMITE), "stoneguard_greatsword");
    public static final Item STONEGUARD_CLUB = registerItem(new ClubItem(AtumMats.KHNUMITE), "stoneguard_club");
    public static final Item STONEGUARD_KHOPESH = registerItem(new KhopeshItem(AtumMats.KHNUMITE), "stoneguard_khopesh");
    public static final Item STONEGUARD_SHIELD = registerItem(new AtumShieldItem(90).setRepairItem(KHNUMITE), "stoneguard_shield");
    public static final Item BRIGAND_SHIELD = registerItem(new AtumShieldItem(150), "brigand_shield");
    public static final Item SCEPTER_ANPUT = registerScepter(God.ANPUT);
    public static final Item SCEPTER_ANUBIS = registerScepter(God.ANUBIS);
    public static final Item SCEPTER_ATEM = registerScepter(God.ATEM);
    public static final Item SCEPTER_GEB = registerScepter(God.GEB);
    public static final Item SCEPTER_HORUS = registerScepter(God.HORUS);
    public static final Item SCEPTER_ISIS = registerScepter(God.ISIS);
    public static final Item SCEPTER_MONTU = registerScepter(God.MONTU);
    public static final Item SCEPTER_NEPTHYS = registerScepter(God.NEPTHYS);
    public static final Item SCEPTER_NUIT = registerScepter(God.NUIT);
    public static final Item SCEPTER_OSIRIS = registerScepter(God.OSIRIS);
    public static final Item SCEPTER_PTAH = registerScepter(God.PTAH);
    public static final Item SCEPTER_RA = registerScepter(God.RA);
    public static final Item SCEPTER_SETH = registerScepter(God.SETH);
    public static final Item SCEPTER_SHU = registerScepter(God.SHU);
    public static final Item SCEPTER_TEFNUT = registerScepter(God.TEFNUT);
    public static final AnputsGroundingItem ANPUTS_GROUNDING = (AnputsGroundingItem) registerItem(new AnputsGroundingItem(), "anputs_grounding");
    public static final Item ANPUTS_HUNGER = registerItem(new AnputsHungerItem(), "anputs_hunger");
    public static final Item ANUBIS_WRATH = registerItem(new AnubisWrathItem(), "anubis_wrath");
    public static final Item EYES_OF_ATEM = registerItem(new AtemArmor(EquipmentSlotType.HEAD), "eyes_of_atem");
    public static final Item BODY_OF_ATEM = registerItem(new AtemArmor(EquipmentSlotType.CHEST), "body_of_atem");
    public static final Item LEGS_OF_ATEM = registerItem(new AtemArmor(EquipmentSlotType.LEGS), "legs_of_atem");
    public static final Item FEET_OF_ATEM = registerItem(new AtemArmor(EquipmentSlotType.FEET), "feet_of_atem");
    public static final Item ATEMS_BOUNTY = registerItem(new AtemsBountyItem(), "atems_bounty");
    public static final Item ATEMS_HOMECOMING = registerItem(new AtemsHomecomingItem(), "atems_homecoming");
    public static final Item ATEMS_PROTECTION = registerItem(new AtemsProtectionItem(), "atems_protection");
    public static final Item ATEMS_WILL = registerItem(new AtemsWillItem(), "atems_will");
    public static final Item GEBS_MIGHT = registerItem(new GebsMightItem(), "gebs_might");
    public static final Item GEBS_TOIL = registerItem(new GebsToilItem(), "gebs_toil");
    public static final Item GEBS_UNDOING = registerItem(new GebsUndoingItem(), "gebs_undoing");
    public static final Item HORUS_ASCENSION = registerItem(new HorusAscensionItem(), "horus_ascension");
    public static final HorusSoaringItem HORUS_SOARING = (HorusSoaringItem) registerItem(new HorusSoaringItem(), "horus_soaring");
    public static final IsisDivisionItem ISIS_DIVISION = (IsisDivisionItem) registerItem(new IsisDivisionItem(), "isis_division");
    public static final Item ISIS_HEALING = registerItem(new IsisHealingItem(), "isis_healing");
    public static final MontusBlastItem MONTUS_BLAST = (MontusBlastItem) registerItem(new MontusBlastItem(), "montus_blast");
    public static final Item MONTUS_STRIKE = registerItem(new MontusStrikeItem(), "montus_strike");
    public static final Item NEPTHYS_BANISHING = registerItem(new NepthysBanishingItem(), "nepthys_banishing");
    public static final Item NEPTHYS_CONSECRATION = registerItem(new NepthysConsecrationItem(), "nepthys_consecration");
    public static final Item NEPTHYS_GUARD = registerItem(new NepthysGuardItem(), "nepthys_guard");
    public static final Item NUITS_IRE = registerItem(new NuitsIreItem(), "nuits_ire");
    public static final Item NUITS_QUARTER = registerItem(new NuitsQuarterItem(), "nuits_quarter");
    public static final Item NUITS_VANISHING = registerItem(new NuitsVanishingItem(), "nuits_vanishing");
    public static final Item OSIRIS_BLESSING = registerItem(new OsirisBlessingItem(), "osiris_blessing");
    public static final Item OSIRIS_MERCY = registerItem(new OsirisMercyItem(), "osiris_mercy");
    public static final Item PTAHS_DECADENCE = registerItem(new PtahsDecadenceItem(), "ptahs_decadence");
    public static final Item HALO_OF_RA = registerItem(new RaArmor(EquipmentSlotType.HEAD), "halo_of_ra");
    public static final Item BODY_OF_RA = registerItem(new RaArmor(EquipmentSlotType.CHEST), "body_of_ra");
    public static final Item LEGS_OF_RA = registerItem(new RaArmor(EquipmentSlotType.LEGS), "legs_of_ra");
    public static final Item FEET_OF_RA = registerItem(new RaArmor(EquipmentSlotType.FEET), "feet_of_ra");
    public static final RasFuryItem RAS_FURY = (RasFuryItem) registerItem(new RasFuryItem(), "ras_fury");
    public static final Item RAS_STEP = registerItem(new RasStep(), "ras_step");
    public static final Item SETHS_STING = registerItem(new SethsStingItem(), "seths_sting");
    public static final SethsVenomItem SETHS_VENOM = (SethsVenomItem) registerItem(new SethsVenomItem(), "seths_venom");
    public static final ShusBreathItem SHUS_BREATH = (ShusBreathItem) registerItem(new ShusBreathItem(), "shus_breath");
    public static final Item SHUS_EXILE = registerItem(new ShusExileItem(), "shus_exile");
    public static final Item SHUS_SWIFTNESS = registerItem(new ShusSwiftnessItem(), "shus_swiftness");
    public static final Item TEFNUTS_CALL = registerItem(new TefnutsCallItem(), "tefnuts_call");
    public static final TefnutsRainItem TEFNUTS_RAIN = (TefnutsRainItem) registerItem(new TefnutsRainItem(), "tefnuts_rain");
    public static final Item MUMMY_HELMET = registerItem(new TexturedArmorItem(AtumMats.MUMMY_ARMOR, "mummy_armor", EquipmentSlotType.HEAD), "mummy_helmet");
    public static final Item MUMMY_CHEST = registerItem(new TexturedArmorItem(AtumMats.MUMMY_ARMOR, "mummy_armor", EquipmentSlotType.CHEST), "mummy_chest");
    public static final Item MUMMY_LEGS = registerItem(new TexturedArmorItem(AtumMats.MUMMY_ARMOR, "mummy_armor", EquipmentSlotType.LEGS), "mummy_legs");
    public static final Item MUMMY_BOOTS = registerItem(new TexturedArmorItem(AtumMats.MUMMY_ARMOR, "mummy_armor", EquipmentSlotType.FEET), "mummy_boots");
    public static final Item WANDERER_HELMET = registerItem(new WandererDyeableArmor(AtumMats.WANDERER_ARMOR, "wanderer_armor", EquipmentSlotType.HEAD), "wanderer_helmet");
    public static final Item WANDERER_CHEST = registerItem(new WandererDyeableArmor(AtumMats.WANDERER_ARMOR, "wanderer_armor", EquipmentSlotType.CHEST), "wanderer_chest");
    public static final Item WANDERER_LEGS = registerItem(new WandererDyeableArmor(AtumMats.WANDERER_ARMOR, "wanderer_armor", EquipmentSlotType.LEGS), "wanderer_legs");
    public static final Item WANDERER_BOOTS = registerItem(new WandererDyeableArmor(AtumMats.WANDERER_ARMOR, "wanderer_armor", EquipmentSlotType.FEET), "wanderer_boots");
    public static final Item DESERT_HELMET_IRON = registerItem(new WandererDyeableArmor(ArmorMaterial.IRON, "desert_iron_armor", EquipmentSlotType.HEAD).setDamageModifier(10), "desert_helmet_iron");
    public static final Item DESERT_CHEST_IRON = registerItem(new WandererDyeableArmor(ArmorMaterial.IRON, "desert_iron_armor", EquipmentSlotType.CHEST).setDamageModifier(10), "desert_chest_iron");
    public static final Item DESERT_LEGS_IRON = registerItem(new WandererDyeableArmor(ArmorMaterial.IRON, "desert_iron_armor", EquipmentSlotType.LEGS).setDamageModifier(10), "desert_legs_iron");
    public static final Item DESERT_BOOTS_IRON = registerItem(new WandererDyeableArmor(ArmorMaterial.IRON, "desert_iron_armor", EquipmentSlotType.FEET).setDamageModifier(10), "desert_boots_iron");
    public static final Item DESERT_HELMET_GOLD = registerItem(new WandererDyeableArmor(ArmorMaterial.GOLD, "desert_gold_armor", EquipmentSlotType.HEAD).setDamageModifier(20), "desert_helmet_gold");
    public static final Item DESERT_CHEST_GOLD = registerItem(new WandererDyeableArmor(ArmorMaterial.GOLD, "desert_gold_armor", EquipmentSlotType.CHEST).setDamageModifier(20), "desert_chest_gold");
    public static final Item DESERT_LEGS_GOLD = registerItem(new WandererDyeableArmor(ArmorMaterial.GOLD, "desert_gold_armor", EquipmentSlotType.LEGS).setDamageModifier(20), "desert_legs_gold");
    public static final Item DESERT_BOOTS_GOLD = registerItem(new WandererDyeableArmor(ArmorMaterial.GOLD, "desert_gold_armor", EquipmentSlotType.FEET).setDamageModifier(20), "desert_boots_gold");
    public static final Item DESERT_HELMET_DIAMOND = registerItem(new WandererDyeableArmor(ArmorMaterial.DIAMOND, "desert_diamond_armor", EquipmentSlotType.HEAD).setDamageModifier(15), "desert_helmet_diamond");
    public static final Item DESERT_CHEST_DIAMOND = registerItem(new WandererDyeableArmor(ArmorMaterial.DIAMOND, "desert_diamond_armor", EquipmentSlotType.CHEST).setDamageModifier(15), "desert_chest_diamond");
    public static final Item DESERT_LEGS_DIAMOND = registerItem(new WandererDyeableArmor(ArmorMaterial.DIAMOND, "desert_diamond_armor", EquipmentSlotType.LEGS).setDamageModifier(15), "desert_legs_diamond");
    public static final Item DESERT_BOOTS_DIAMOND = registerItem(new WandererDyeableArmor(ArmorMaterial.DIAMOND, "desert_diamond_armor", EquipmentSlotType.FEET).setDamageModifier(15), "desert_boots_diamond");
    public static final Item DESERT_WOLF_IRON_ARMOR = registerItem(new NonStackableItem(), "desert_wolf_iron_armor");
    public static final Item DESERT_WOLF_GOLD_ARMOR = registerItem(new NonStackableItem(), "desert_wolf_gold_armor");
    public static final Item DESERT_WOLF_DIAMOND_ARMOR = registerItem(new NonStackableItem(), "desert_wolf_diamond_armor");
    public static final Item CAMEL_IRON_ARMOR = registerItem(new NonStackableItem(), "camel_iron_armor");
    public static final Item CAMEL_GOLD_ARMOR = registerItem(new NonStackableItem(), "camel_gold_armor");
    public static final Item CAMEL_DIAMOND_ARMOR = registerItem(new NonStackableItem(), "camel_diamond_armor");
    public static final Item SCROLL = registerItem(new SimpleItem(), "scroll");
    public static final Item SCRAP = registerItem(new SimpleItem(), "cloth_scrap");
    public static final Item LINEN_BANDAGE = registerItem(new LinenBandageItem(), "linen_bandage");
    public static final Item LINEN_THREAD = registerItem(new SimpleItem(), "linen_thread");
    public static final Item LINEN_CLOTH = registerItem(new SimpleItem(), "linen_cloth");
    public static final Item PAPYRUS_PLANT = registerItem(new BlockItem(AtumBlocks.PAPYRUS, new Item.Properties().group(Atum.GROUP)), "papyrus_plant");
    public static final Item FLAX_SEEDS = registerItem(new BlockNamedItem(AtumBlocks.FLAX, new Item.Properties().group(Atum.GROUP)), "flax_seeds");
    public static final Item FLAX = registerItem(new SimpleItem(), "flax");
    public static final Item OPHIDIAN_TONGUE_FLOWER = registerItem(new SimpleItem(), "ophidian_tongue_flower");
    public static final Item ANPUTS_FINGERS_SPORES = registerItem(new BlockNamedItem(AtumBlocks.ANPUTS_FINGERS, new Item.Properties().group(Atum.GROUP)), "anputs_fingers_spores");
    public static final Item EMMER_SEEDS = registerItem(new BlockNamedItem(AtumBlocks.EMMER_WHEAT, new Item.Properties().group(Atum.GROUP)), "emmer_seeds");
    public static final Item EMMER = registerItem(new SimpleItem(), "emmer");
    public static final Item EMMER_FLOUR = registerItem(new EmmerFlourItem(), "emmer_flour");
    public static final Item EMMER_DOUGH = registerItem(new SimpleItem(), "emmer_dough");
    public static final Item EMMER_BREAD = registerItem(new Item(new Item.Properties().food(AtumFoods.EMMER_BREAD).group(Atum.GROUP)), "emmer_bread");
    public static final Item QUAIL_EGG = registerItem(new QuailEggItem(), "quail_egg");
    public static final Item CAMEL_RAW = registerItem(new Item(new Item.Properties().food(AtumFoods.CAMEL_RAW).group(Atum.GROUP)), "camel");
    public static final Item CAMEL_COOKED = registerItem(new Item(new Item.Properties().food(AtumFoods.CAMEL_COOKED).group(Atum.GROUP)), "camel_cooked");
    public static final Item QUAIL_RAW = registerItem(new Item(new Item.Properties().food(AtumFoods.QUAIL_RAW).group(Atum.GROUP)), "quail");
    public static final Item QUAIL_COOKED = registerItem(new Item(new Item.Properties().food(AtumFoods.QUAIL_COOKED).group(Atum.GROUP)), "quail_cooked");
    public static final Item DATE = registerItem(new Item(new Item.Properties().food(Foods.APPLE).group(Atum.GROUP)), "date");
    public static final Item GLISTERING_DATE = registerItem(new SimpleItem(), "glistering_date");
    public static final Item GOLDEN_DATE = registerItem(new Item(new Item.Properties().food(AtumFoods.GOLDEN_DATE).group(Atum.GROUP)), "golden_date");
    public static final Item ENCHANTED_GOLDEN_DATE = registerItem(new EnchantedGoldenAppleItem(new Item.Properties().food(AtumFoods.ENCHANTED_GOLDEN_DATE).group(Atum.GROUP)), "golden_date_enchanted");
    public static final Item ECTOPLASM = registerItem(new SimpleItem(), "ectoplasm");
    public static final Item MANDIBLES = registerItem(new SimpleItem(), "mandibles");
    public static final Item DUSTY_BONE = registerItem(new SimpleItem(), "dusty_bone");
    public static final Item WOLF_PELT = registerItem(new SimpleItem(), "wolf_pelt");
    public static final Item FERTILE_SOIL_PILE = registerItem(new SimpleItem(), "fertile_soil_pile");
    public static final Item FORSAKEN_FISH = registerItem(new FishItem(FishItem.FishType.FORSAKEN), "fish_forsaken");
    public static final Item MUMMIFIED_FISH = registerItem(new FishItem(FishItem.FishType.MUMMIFIED), "fish_mummified");
    public static final Item JEWELED_FISH = registerItem(new FishItem(FishItem.FishType.JEWELED), "fish_jeweled");
    public static final Item SKELETAL_FISH = registerItem(new FishItem(FishItem.FishType.SKELETAL), "fish_skeletal");
    public static final Item CRUNCHY_SCARAB = registerItem(new CrunchyScarabItem(new Item.Properties().food(AtumFoods.CRUNCHY_SCARAB)), "crunchy_scarab");
    public static final Item CRUNCHY_GOLD_SCARAB = registerItem(new CrunchyScarabItem(new Item.Properties().food(AtumFoods.CRUNCHY_GOLD_SCARAB)), "crunchy_golden_scarab");

    public static void setItemInfo() {

    }

    public static class AtumFoods {
        public static final Food EMMER_BREAD = new Food.Builder().hunger(4).saturation(0.9F).build();
        public static final Food CAMEL_RAW = new Food.Builder().hunger(3).saturation(0.2F).meat().build();
        public static final Food CAMEL_COOKED = new Food.Builder().hunger(9).saturation(0.7F).meat().build();
        public static final Food QUAIL_RAW = new Food.Builder().hunger(1).saturation(0.4F).meat().build();
        public static final Food QUAIL_COOKED = new Food.Builder().hunger(5).saturation(0.8F).meat().build();
        public static final Food GOLDEN_DATE = new Food.Builder().hunger(5).saturation(1.5F).effect(() -> new EffectInstance(Effects.REGENERATION, 100, 1), 1.0F).effect(new EffectInstance(Effects.ABSORPTION, 2400, 0), 1.0F).setAlwaysEdible().build();
        public static final Food ENCHANTED_GOLDEN_DATE = new Food.Builder().hunger(5).saturation(1.5F).effect(() -> new EffectInstance(Effects.REGENERATION, 400, 1), 1.0F).effect(() -> new EffectInstance(Effects.RESISTANCE, 6000, 0), 1.0F).effect(() -> new EffectInstance(Effects.FIRE_RESISTANCE, 6000, 0), 1.0F).effect(() -> new EffectInstance(Effects.ABSORPTION, 2400, 3), 1.0F).setAlwaysEdible().build();
        public static final Food CRUNCHY_SCARAB = new Food.Builder().hunger(3).saturation(0.1F).meat().build();
        public static final Food CRUNCHY_GOLD_SCARAB = new Food.Builder().hunger(6).saturation(1.3F).meat().build();
    }
}