package com.teammetallurgy.atum.init;

import com.teammetallurgy.atum.Atum;
import com.teammetallurgy.atum.blocks.AtumOresBlock;
import com.teammetallurgy.atum.blocks.PortalBlock;
import com.teammetallurgy.atum.blocks.SandLayersBlock;
import com.teammetallurgy.atum.blocks.StrangeSandBlock;
import com.teammetallurgy.atum.blocks.base.AtumPaneBlock;
import com.teammetallurgy.atum.blocks.base.DoorAtumBlock;
import com.teammetallurgy.atum.blocks.linen.LinenBlock;
import com.teammetallurgy.atum.blocks.linen.LinenCarpetBlock;
import com.teammetallurgy.atum.blocks.machines.KilnBlock;
import com.teammetallurgy.atum.blocks.machines.KilnFakeBlock;
import com.teammetallurgy.atum.blocks.machines.QuernBlock;
import com.teammetallurgy.atum.blocks.machines.SpinningWheelBlock;
import com.teammetallurgy.atum.blocks.stone.ceramic.CeramicBlock;
import com.teammetallurgy.atum.blocks.stone.ceramic.CeramicTileBlock;
import com.teammetallurgy.atum.blocks.stone.khnumite.KhnumiteBlock;
import com.teammetallurgy.atum.blocks.stone.khnumite.KhnumiteFaceBlock;
import com.teammetallurgy.atum.blocks.stone.limestone.*;
import com.teammetallurgy.atum.blocks.stone.limestone.chest.ChestSpawnerBlock;
import com.teammetallurgy.atum.blocks.stone.limestone.chest.LimestoneChestBlock;
import com.teammetallurgy.atum.blocks.stone.limestone.chest.SarcophagusBlock;
import com.teammetallurgy.atum.blocks.trap.*;
import com.teammetallurgy.atum.blocks.vegetation.*;
import com.teammetallurgy.atum.blocks.wood.*;
import com.teammetallurgy.atum.client.render.ItemStackRenderer;
import net.minecraft.block.*;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraft.entity.EntityType;
import net.minecraft.item.DyeColor;
import net.minecraft.item.Item;
import net.minecraft.util.Direction;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.IBlockReader;
import net.minecraftforge.common.ToolType;
import net.minecraftforge.registries.ObjectHolder;

import static com.teammetallurgy.atum.misc.AtumRegistry.*;
import static net.minecraft.block.AbstractBlock.Properties.create;
import static net.minecraft.block.AbstractBlock.Properties.from;

@ObjectHolder(value = Atum.MOD_ID)
public class AtumBlocks {
    public static final PortalBlock PORTAL = (PortalBlock) registerBlock(new PortalBlock(), null, "portal");
    public static final Block CHEST_SPAWNER = registerBlock(new ChestSpawnerBlock(), () -> ItemStackRenderer::new, null, "chest_spawner");
    public static final Block SAND = registerBlock(new StrangeSandBlock(), "sand");
    public static final Block SAND_LAYERED = registerBlock(new SandLayersBlock(), "sand_layer");
    public static final Block DATE_BLOCK = registerBlock(new DateBlock(), null, "date_block");
    public static final Block EMMER_WHEAT = registerBlock(new EmmerBlock(), null, "emmer_wheat");
    public static final Block ANPUTS_FINGERS = registerBlock(new AnputsFingersBlock(), null, "anputs_fingers");
    public static final Block OASIS_GRASS = registerBlock(new OasisGrassBlock(), "oasis_grass");
    public static final Block DRY_GRASS = registerBlock(new DryGrassBlock(), "dry_grass");
    public static final Block TALL_DRY_GRASS = registerBlock(new TallDryGrass(), "tall_dry_grass");
    public static final Block SHRUB = registerBlock(new ShrubBlock(), "shrub");
    public static final Block WEED = registerBlock(new ShrubBlock(), "weed");
    public static final Block PAPYRUS = registerBlock(new PapyrusBlock(), null, "papyrus");
    public static final Block OPHIDIAN_TONGUE = registerBlock(new OphidianTongueBlock(), "ophidian_tongue");
    public static final Block FLAX = registerBlock(new FlaxBlock(), null, "flax_block");
    public static final Block FERTILE_SOIL = registerBlock(new FertileSoilBlock(), "fertile_soil");
    public static final Block FERTILE_SOIL_TILLED = registerBlock(new FertileSoilTilledBlock(), "fertile_soil_tilled");
    public static final Block FERTILE_SOIL_PATH = registerBlock(new AtumPathBlock(FERTILE_SOIL), "fertile_soil_path");
    public static final Block STRANGE_SAND_PATH = registerBlock(new AtumPathBlock(SAND), "strange_sand_path");
    public static final Block QUERN = registerBlock(new QuernBlock(), "quern");
    public static final Block SPINNING_WHEEL = registerBlock(new SpinningWheelBlock(), "spinning_wheel");
    public static final Block KILN = registerBlock(new KilnBlock(), "kiln");
    public static final Block KILN_FAKE = registerBlock(new KilnFakeBlock(), null, "kiln_fake");
    public static final Block BURNING_TRAP = registerBlock(new BurningTrapBlock(), "burning_trap");
    public static final Block POISON_TRAP = registerBlock(new PoisonTrapBlock(), "poison_trap");
    public static final Block TAR_TRAP = registerBlock(new TarTrapBlock(), "tar_trap");
    public static final Block SMOKE_TRAP = registerBlock(new SmokeTrapBlock(), "smoke_trap");
    public static final Block ARROW_TRAP = registerBlock(new ArrowTrapBlock(), "arrow_trap");
    public static final Block SARCOPHAGUS = registerBlock(new SarcophagusBlock(), () -> ItemStackRenderer::new, new Item.Properties(), "sarcophagus");
    public static final Block LIMESTONE_CHEST = registerBlock(new LimestoneChestBlock(), () -> ItemStackRenderer::new, new Item.Properties(), "limestone_chest");
    public static final Block GOLD_ORE = registerBlock(new AtumOresBlock(create(Material.ROCK).hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(2)), "gold_ore");
    public static final Block IRON_ORE = registerBlock(new AtumOresBlock(create(Material.ROCK).hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(1)), "iron_ore");
    public static final Block COAL_ORE = registerBlock(new AtumOresBlock(create(Material.ROCK).hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(0)), "coal_ore");
    public static final Block LAPIS_ORE = registerBlock(new AtumOresBlock(create(Material.ROCK).hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(1)), "lapis_ore");
    public static final Block DIAMOND_ORE = registerBlock(new AtumOresBlock(create(Material.ROCK).hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(2)), "diamond_ore");
    public static final Block EMERALD_ORE = registerBlock(new AtumOresBlock(create(Material.ROCK).hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(2)), "emerald_ore");
    public static final Block REDSTONE_ORE = registerBlock(new RedstoneOreBlock(create(Material.ROCK).tickRandomly().setLightLevel(s -> 9).hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(2)), "redstone_ore");
    public static final Block BONE_ORE = registerBlock(new AtumOresBlock(create(Material.ROCK).hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(0)), "bone_ore");
    public static final Block RELIC_ORE = registerBlock(new AtumOresBlock(create(Material.ROCK).hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(1)), "relic_ore");
    public static final Block KHNUMITE_RAW = registerBlock(new Block(create(Material.CLAY).hardnessAndResistance(0.6F).sound(SoundType.GROUND).harvestTool(ToolType.SHOVEL).harvestLevel(0)), "khnumite_raw");
    public static final Block DIRTY_BONE = registerBlock(new RotatedPillarBlock(create(Material.ROCK, MaterialColor.SAND).hardnessAndResistance(2.0F)), "dirty_bone_block");
    public static final Block DIRTY_BONE_SLAB = registerBlock(new SlabBlock(create(Material.ROCK, MaterialColor.SAND).hardnessAndResistance(2.0F)), "dirty_bone_slab");
    public static final Block BONE_LADDER = registerBlock(new AtumLadderBlock(), "bone_ladder");
    public static final Block LIMESTONE_FURNACE = registerBlock(new LimestoneFurnaceBlock(), "limestone_furnace");
    public static final Block PALM_TORCH = registerTorch(new AtumTorchBlock(14), "palm_torch");
    public static final Block DEADWOOD_TORCH = registerTorch(new AtumTorchBlock(14), "deadwood_torch");
    public static final Block LIMESTONE_TORCH = registerTorch(new AtumTorchBlock(14), "limestone_torch");
    public static final Block BONE_TORCH = registerTorch(new AtumTorchBlock(14), "bone_torch");
    public static final Block PHARAOH_TORCH = registerTorch(new AtumTorchBlock(14), "pharaoh_torch");
    public static final Block LIMESTONE_GRAVEL = registerBlock(new LimestoneGravelBlock(), "limestone_gravel");
    public static final Block MARL = registerBlock(new Block(create(Material.CLAY).hardnessAndResistance(0.6F).sound(SoundType.GROUND).harvestTool(ToolType.SHOVEL).harvestLevel(0)), "marl");
    public static final Block RA_STONE = registerBlock(new RaStoneBlock(), null, "ra_stone");
    public static final Block LIMESTONE = registerBlock(new LimestoneBlock(), "limestone");
    public static final Block LIMESTONE_CRACKED = registerBlock(new Block(create(Material.ROCK, MaterialColor.SAND).hardnessAndResistance(1.5F, 10.0F).harvestTool(ToolType.PICKAXE).harvestLevel(0)), "limestone_cracked");
    public static final Block LIMESTONE_BRICK_SMALL = registerBlock(new LimestoneBrickBlock(), "limestone_brick_small");
    public static final Block LIMESTONE_BRICK_LARGE = registerBlock(new LimestoneBrickBlock(), "limestone_brick_large");
    public static final Block LIMESTONE_BRICK_CRACKED_BRICK = registerBlock(new LimestoneBrickBlock(), "limestone_brick_cracked_brick");
    public static final Block LIMESTONE_BRICK_CHISELED = registerBlock(new LimestoneBrickBlock(), "limestone_brick_chiseled");
    public static final Block LIMESTONE_BRICK_CARVED = registerBlock(new LimestoneBrickBlock(), "limestone_brick_carved");
    public static final Block LIMESTONE_SLAB = registerBlock(new SlabBlock(create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), "limestone_slab");
    public static final Block LIMESTONE_CRACKED_SLAB = registerBlock(new SlabBlock(create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), "limestone_cracked_slab");
    public static final Block LIMESTONE_BRICK_SMALL_SLAB = registerBlock(new SlabBlock(create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), "limestone_small_slab");
    public static final Block LIMESTONE_BRICK_LARGE_SLAB = registerBlock(new SlabBlock(create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), "limestone_large_slab");
    public static final Block LIMESTONE_CRACKED_BRICK_SLAB = registerBlock(new SlabBlock(create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), "limestone_cracked_brick_slab");
    public static final Block LIMESTONE_BRICK_CHISELED_SLAB = registerBlock(new SlabBlock(create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), "limestone_chiseled_slab");
    public static final Block LIMESTONE_BRICK_CARVED_SLAB = registerBlock(new SlabBlock(create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)), "limestone_carved_slab");
    public static final Block KHNUMITE_BLOCK = registerBlock(new KhnumiteBlock(), "khnumite_block");
    public static final Block KHNUMITE_FACE = registerBlock(new KhnumiteFaceBlock(), "khnumite_face");
    public static final Block SMOOTH_STAIRS = registerBlock(new StairsBlock(LIMESTONE::getDefaultState, from(LIMESTONE)), "smooth_stairs");
    public static final Block CRACKED_STAIRS = registerBlock(new StairsBlock(LIMESTONE_CRACKED::getDefaultState, from(LIMESTONE_CRACKED)), "cracked_stairs");
    public static final Block SMALL_STAIRS = registerBlock(new StairsBlock(LIMESTONE_BRICK_SMALL::getDefaultState, from(LIMESTONE_BRICK_SMALL)), "small_stairs");
    public static final Block LARGE_STAIRS = registerBlock(new StairsBlock(LIMESTONE_BRICK_LARGE::getDefaultState, from(LIMESTONE_BRICK_LARGE)), "large_stairs");
    public static final Block CRACKED_BRICK_STAIRS = registerBlock(new StairsBlock(LIMESTONE_BRICK_CRACKED_BRICK::getDefaultState, from(LIMESTONE_BRICK_CRACKED_BRICK)), "cracked_brick_stairs");
    public static final Block CHISELED_STAIRS = registerBlock(new StairsBlock(LIMESTONE_BRICK_CHISELED::getDefaultState, from(LIMESTONE_BRICK_CHISELED)), "chiseled_stairs");
    public static final Block CARVED_STAIRS = registerBlock(new StairsBlock(LIMESTONE_BRICK_CARVED::getDefaultState, from(LIMESTONE_BRICK_CARVED)), "carved_stairs");
    public static final WallBlock LIMESTONE_WALL = (WallBlock) registerBlock(new WallBlock(from(LIMESTONE)), "limestone_wall");
    public static final WallBlock LIMESTONE_CRACKED_WALL = (WallBlock) registerBlock(new WallBlock(from(LIMESTONE_CRACKED)), "limestone_cracked_wall");
    public static final WallBlock SMALL_WALL = (WallBlock) registerBlock(new WallBlock(from(LIMESTONE_BRICK_SMALL)), "small_wall");
    public static final WallBlock LARGE_WALL = (WallBlock) registerBlock(new WallBlock(from(LIMESTONE_BRICK_LARGE)), "large_wall");
    public static final WallBlock CRACKED_BRICK_WALL = (WallBlock) registerBlock(new WallBlock(from(LIMESTONE_BRICK_CRACKED_BRICK)), "cracked_brick_wall");
    public static final WallBlock CHISELED_WALL = (WallBlock) registerBlock(new WallBlock(from(LIMESTONE_BRICK_CHISELED)), "chiseled_wall");
    public static final WallBlock CARVED_WALL = (WallBlock) registerBlock(new WallBlock(from(LIMESTONE_BRICK_CARVED)), "carved_wall");
    public static final Block LIMESTONE_DOOR = registerBlock(new DoorAtumBlock(from(LIMESTONE)), "limestone_door");
    public static final Block LIMESTONE_CRACKED_DOOR = registerBlock(new DoorAtumBlock(from(LIMESTONE_CRACKED)), "limestone_cracked_door");
    public static final Block LIMESTONE_BRICK_SMALL_DOOR = registerBlock(new DoorAtumBlock(from(LIMESTONE_BRICK_SMALL)), "limestone_brick_small_door");
    public static final Block LIMESTONE_BRICK_LARGE_DOOR = registerBlock(new DoorAtumBlock(from(LIMESTONE_BRICK_LARGE)), "limestone_brick_large_door");
    public static final Block LIMESTONE_CRACKED_BRICK_DOOR = registerBlock(new DoorAtumBlock(from(LIMESTONE_BRICK_CRACKED_BRICK)), "limestone_brick_cracked_brick_door");
    public static final Block LIMESTONE_BRICK_CHISELED_DOOR = registerBlock(new DoorAtumBlock(from(LIMESTONE_BRICK_CHISELED)), "limestone_brick_chiseled_door");
    public static final Block LIMESTONE_BRICK_CARVED_DOOR = registerBlock(new DoorAtumBlock(from(LIMESTONE_BRICK_CARVED)), "limestone_brick_carved_door");
    public static final Block ALABASTER = registerBlock(new Block(create(Material.ROCK, MaterialColor.QUARTZ).hardnessAndResistance(2.0F, 8.0F).sound(SoundType.STONE).harvestTool(ToolType.PICKAXE).harvestLevel(0)), "alabaster");
    public static final Block ALABASTER_BRICK_SMOOTH = registerBlock(new Block(from(ALABASTER)), "alabaster_brick_smooth");
    public static final Block ALABASTER_BRICK_POLISHED = registerBlock(new Block(from(ALABASTER)), "alabaster_brick_polished");
    public static final Block ALABASTER_BRICK_CARVED = registerBlock(new Block(from(ALABASTER)), "alabaster_brick_carved");
    public static final Block ALABASTER_BRICK_TILED = registerBlock(new Block(from(ALABASTER)), "alabaster_brick_tiled");
    public static final Block ALABASTER_BRICK_PILLAR = registerBlock(new Block(from(ALABASTER)), "alabaster_brick_pillar");
    public static final Block ALABASTER_BRICK_SMOOTH_SLAB = registerBlock(new SlabBlock(from(ALABASTER)), "alabaster_smooth_slab");
    public static final Block ALABASTER_BRICK_POLISHED_SLAB = registerBlock(new SlabBlock(from(ALABASTER)), "alabaster_polished_slab");
    public static final Block ALABASTER_BRICK_CARVED_SLAB = registerBlock(new SlabBlock(from(ALABASTER)), "alabaster_carved_slab");
    public static final Block ALABASTER_BRICK_TILED_SLAB = registerBlock(new SlabBlock(from(ALABASTER)), "alabaster_tiled_slab");
    public static final Block ALABASTER_BRICK_PILLAR_SLAB = registerBlock(new SlabBlock(from(ALABASTER)), "alabaster_pillar_slab");
    public static final Block ALABASTER_BRICK_SMOOTH_STAIRS = registerBlock(new StairsBlock(ALABASTER_BRICK_SMOOTH::getDefaultState, from(ALABASTER)), "alabaster_smooth_stairs");
    public static final Block ALABASTER_BRICK_POLISHED_STAIRS = registerBlock(new StairsBlock(ALABASTER_BRICK_POLISHED::getDefaultState, from(ALABASTER)), "alabaster_polished_stairs");
    public static final Block ALABASTER_BRICK_CARVED_STAIRS = registerBlock(new StairsBlock(ALABASTER_BRICK_CARVED::getDefaultState, from(ALABASTER)), "alabaster_carved_stairs");
    public static final Block ALABASTER_BRICK_TILED_STAIRS = registerBlock(new StairsBlock(ALABASTER_BRICK_TILED::getDefaultState, from(ALABASTER)), "alabaster_tiled_stairs");
    public static final Block ALABASTER_BRICK_PILLAR_STARS = registerBlock(new StairsBlock(ALABASTER_BRICK_PILLAR::getDefaultState, from(ALABASTER)), "alabaster_pillar_stairs");
    public static final WallBlock ALABASTER_BRICK_SMOOTH_WALL = (WallBlock) registerBlock(new WallBlock(from(ALABASTER)), "alabaster_smooth_wall");
    public static final WallBlock ALABASTER_BRICK_POLISHED_WALL = (WallBlock) registerBlock(new WallBlock(from(ALABASTER)), "alabaster_polished_wall");
    public static final WallBlock ALABASTER_BRICK_CARVED_WALL = (WallBlock) registerBlock(new WallBlock(from(ALABASTER)), "alabaster_carved_wall");
    public static final WallBlock ALABASTER_BRICK_TILED_WALL = (WallBlock) registerBlock(new WallBlock(from(ALABASTER)), "alabaster_tiled_wall");
    public static final WallBlock ALABASTER_BRICK_PILLAR_WALL = (WallBlock) registerBlock(new WallBlock(from(ALABASTER)), "alabaster_pillar_wall");
    public static final Block PORPHYRY = registerBlock(new Block(create(Material.ROCK, MaterialColor.BLACK).hardnessAndResistance(1.5F, 5.0F).sound(SoundType.STONE).harvestTool(ToolType.PICKAXE).harvestLevel(0)), "porphyry");
    public static final Block PORPHYRY_BRICK_SMOOTH = registerBlock(new Block(from(PORPHYRY)), "porphyry_brick_smooth");
    public static final Block PORPHYRY_BRICK_POLISHED = registerBlock(new Block(from(PORPHYRY)), "porphyry_brick_polished");
    public static final Block PORPHYRY_BRICK_CARVED = registerBlock(new Block(from(PORPHYRY)), "porphyry_brick_carved");
    public static final Block PORPHYRY_BRICK_TILED = registerBlock(new Block(from(PORPHYRY)), "porphyry_brick_tiled");
    public static final Block PORPHYRY_BRICK_PILLAR = registerBlock(new Block(from(PORPHYRY)), "porphyry_brick_pillar");
    public static final Block PORPHYRY_BRICK_SMOOTH_SLAB = registerBlock(new SlabBlock(from(PORPHYRY)), "porphyry_smooth_slab");
    public static final Block PORPHYRY_BRICK_POLISHED_SLAB = registerBlock(new SlabBlock(from(PORPHYRY)), "porphyry_polished_slab");
    public static final Block PORPHYRY_BRICK_CARVED_SLAB = registerBlock(new SlabBlock(from(PORPHYRY)), "porphyry_carved_slab");
    public static final Block PORPHYRY_BRICK_TILED_SLAB = registerBlock(new SlabBlock(from(PORPHYRY)), "porphyry_tiled_slab");
    public static final Block PORPHYRY_BRICK_PILLAR_SLAB = registerBlock(new SlabBlock(from(PORPHYRY)), "porphyry_pillar_slab");
    public static final Block PORPHYRY_BRICK_SMOOTH_STAIRS = registerBlock(new StairsBlock(PORPHYRY_BRICK_SMOOTH::getDefaultState, from(PORPHYRY)), "porphyry_smooth_stairs");
    public static final Block PORPHYRY_BRICK_POLISHED_STAIRS = registerBlock(new StairsBlock(PORPHYRY_BRICK_POLISHED::getDefaultState, from(PORPHYRY)), "porphyry_polished_stairs");
    public static final Block PORPHYRY_BRICK_CARVED_STAIRS = registerBlock(new StairsBlock(PORPHYRY_BRICK_CARVED::getDefaultState, from(PORPHYRY)), "porphyry_carved_stairs");
    public static final Block PORPHYRY_BRICK_TILED_STAIRS = registerBlock(new StairsBlock(PORPHYRY_BRICK_TILED::getDefaultState, from(PORPHYRY)), "porphyry_tiled_stairs");
    public static final Block PORPHYRY_BRICK_PILLAR_STARS = registerBlock(new StairsBlock(PORPHYRY_BRICK_PILLAR::getDefaultState, from(PORPHYRY)), "porphyry_pillar_stairs");
    public static final WallBlock PORPHYRY_BRICK_SMOOTH_WALL = (WallBlock) registerBlock(new WallBlock(from(PORPHYRY)), "porphyry_smooth_wall");
    public static final WallBlock PORPHYRY_BRICK_POLISHED_WALL = (WallBlock) registerBlock(new WallBlock(from(PORPHYRY)), "porphyry_polished_wall");
    public static final WallBlock PORPHYRY_BRICK_CARVED_WALL = (WallBlock) registerBlock(new WallBlock(from(PORPHYRY)), "porphyry_carved_wall");
    public static final WallBlock PORPHYRY_BRICK_TILED_WALL = (WallBlock) registerBlock(new WallBlock(from(PORPHYRY)), "porphyry_tiled_wall");
    public static final WallBlock PORPHYRY_BRICK_PILLAR_WALL = (WallBlock) registerBlock(new WallBlock(from(PORPHYRY)), "porphyry_pillar_wall");
    public static final Block CERAMIC_WHITE = registerBlock(new CeramicBlock(DyeColor.WHITE), "ceramic_white");
    public static final Block CERAMIC_ORANGE = registerBlock(new CeramicBlock(DyeColor.ORANGE), "ceramic_orange");
    public static final Block CERAMIC_MAGENTA = registerBlock(new CeramicBlock(DyeColor.MAGENTA), "ceramic_magenta");
    public static final Block CERAMIC_LIGHT_BLUE = registerBlock(new CeramicBlock(DyeColor.LIGHT_BLUE), "ceramic_light_blue");
    public static final Block CERAMIC_YELLOW = registerBlock(new CeramicBlock(DyeColor.YELLOW), "ceramic_yellow");
    public static final Block CERAMIC_LIME = registerBlock(new CeramicBlock(DyeColor.LIME), "ceramic_lime");
    public static final Block CERAMIC_PINK = registerBlock(new CeramicBlock(DyeColor.PINK), "ceramic_pink");
    public static final Block CERAMIC_GRAY = registerBlock(new CeramicBlock(DyeColor.GRAY), "ceramic_gray");
    public static final Block CERAMIC_LIGHT_GRAY = registerBlock(new CeramicBlock(DyeColor.LIGHT_GRAY), "ceramic_light_gray");
    public static final Block CERAMIC_CYAN = registerBlock(new CeramicBlock(DyeColor.CYAN), "ceramic_cyan");
    public static final Block CERAMIC_PURPLE = registerBlock(new CeramicBlock(DyeColor.PURPLE), "ceramic_purple");
    public static final Block CERAMIC_BLUE = registerBlock(new CeramicBlock(DyeColor.BLUE), "ceramic_blue");
    public static final Block CERAMIC_BROWN = registerBlock(new CeramicBlock(DyeColor.BROWN), "ceramic_brown");
    public static final Block CERAMIC_GREEN = registerBlock(new CeramicBlock(DyeColor.GREEN), "ceramic_green");
    public static final Block CERAMIC_RED = registerBlock(new CeramicBlock(DyeColor.RED), "ceramic_red");
    public static final Block CERAMIC_BLACK = registerBlock(new CeramicBlock(DyeColor.BLACK), "ceramic_black");
    public static final Block CERAMIC_WHITE_SLAB = registerBlock(new SlabBlock(from(CERAMIC_WHITE)), "ceramic_slab_white");
    public static final Block CERAMIC_ORANGE_SLAB = registerBlock(new SlabBlock(from(CERAMIC_ORANGE)), "ceramic_slab_orange");
    public static final Block CERAMIC_MAGENTA_SLAB = registerBlock(new SlabBlock(from(CERAMIC_MAGENTA)), "ceramic_slab_magenta");
    public static final Block CERAMIC_LIGHT_BLUE_SLAB = registerBlock(new SlabBlock(from(CERAMIC_LIGHT_BLUE)), "ceramic_slab_light_blue");
    public static final Block CERAMIC_YELLOW_SLAB = registerBlock(new SlabBlock(from(CERAMIC_YELLOW)), "ceramic_slab_yellow");
    public static final Block CERAMIC_LIME_SLAB = registerBlock(new SlabBlock(from(CERAMIC_LIME)), "ceramic_slab_lime");
    public static final Block CERAMIC_PINK_SLAB = registerBlock(new SlabBlock(from(CERAMIC_PINK)), "ceramic_slab_pink");
    public static final Block CERAMIC_GRAY_SLAB = registerBlock(new SlabBlock(from(CERAMIC_GRAY)), "ceramic_slab_gray");
    public static final Block CERAMIC_LIGHT_GRAY_SLAB = registerBlock(new SlabBlock(from(CERAMIC_LIGHT_GRAY)), "ceramic_slab_light_gray");
    public static final Block CERAMIC_CYAN_SLAB = registerBlock(new SlabBlock(from(CERAMIC_CYAN)), "ceramic_slab_cyan");
    public static final Block CERAMIC_PURPLE_SLAB = registerBlock(new SlabBlock(from(CERAMIC_PURPLE)), "ceramic_slab_purple");
    public static final Block CERAMIC_BLUE_SLAB = registerBlock(new SlabBlock(from(CERAMIC_BLUE)), "ceramic_slab_blue");
    public static final Block CERAMIC_BROWN_SLAB = registerBlock(new SlabBlock(from(CERAMIC_BROWN)), "ceramic_slab_brown");
    public static final Block CERAMIC_GREEN_SLAB = registerBlock(new SlabBlock(from(CERAMIC_GREEN)), "ceramic_slab_green");
    public static final Block CERAMIC_RED_SLAB = registerBlock(new SlabBlock(from(CERAMIC_RED)), "ceramic_slab_red");
    public static final Block CERAMIC_BLACK_SLAB = registerBlock(new SlabBlock(from(CERAMIC_BLACK)), "ceramic_slab_black");
    public static final Block CERAMIC_WHITE_TILE = registerBlock(new CeramicTileBlock(from(CERAMIC_WHITE)), "ceramic_tile_white");
    public static final Block CERAMIC_ORANGE_TILE = registerBlock(new CeramicTileBlock(from(CERAMIC_ORANGE)), "ceramic_tile_orange");
    public static final Block CERAMIC_MAGENTA_TILE = registerBlock(new CeramicTileBlock(from(CERAMIC_MAGENTA)), "ceramic_tile_magenta");
    public static final Block CERAMIC_LIGHT_BLUE_TILE = registerBlock(new CeramicTileBlock(from(CERAMIC_LIGHT_BLUE)), "ceramic_tile_light_blue");
    public static final Block CERAMIC_YELLOW_TILE = registerBlock(new CeramicTileBlock(from(CERAMIC_YELLOW)), "ceramic_tile_yellow");
    public static final Block CERAMIC_LIME_TILE = registerBlock(new CeramicTileBlock(from(CERAMIC_LIME)), "ceramic_tile_lime");
    public static final Block CERAMIC_PINK_TILE = registerBlock(new CeramicTileBlock(from(CERAMIC_PINK)), "ceramic_tile_pink");
    public static final Block CERAMIC_GRAY_TILE = registerBlock(new CeramicTileBlock(from(CERAMIC_GRAY)), "ceramic_tile_gray");
    public static final Block CERAMIC_LIGHT_GRAY_TILE = registerBlock(new CeramicTileBlock(from(CERAMIC_LIGHT_GRAY)), "ceramic_tile_light_gray");
    public static final Block CERAMIC_CYAN_TILE = registerBlock(new CeramicTileBlock(from(CERAMIC_CYAN)), "ceramic_tile_cyan");
    public static final Block CERAMIC_PURPLE_TILE = registerBlock(new CeramicTileBlock(from(CERAMIC_PURPLE)), "ceramic_tile_purple");
    public static final Block CERAMIC_BLUE_TILE = registerBlock(new CeramicTileBlock(from(CERAMIC_BLUE)), "ceramic_tile_blue");
    public static final Block CERAMIC_BROWN_TILE = registerBlock(new CeramicTileBlock(from(CERAMIC_BROWN)), "ceramic_tile_brown");
    public static final Block CERAMIC_GREEN_TILE = registerBlock(new CeramicTileBlock(from(CERAMIC_GREEN)), "ceramic_tile_green");
    public static final Block CERAMIC_RED_TILE = registerBlock(new CeramicTileBlock(from(CERAMIC_RED)), "ceramic_tile_red");
    public static final Block CERAMIC_BLACK_TILE = registerBlock(new CeramicTileBlock(from(CERAMIC_BLACK)), "ceramic_tile_black");
    public static final Block CERAMIC_WHITE_STAIRS = registerBlock(new StairsBlock(CERAMIC_WHITE::getDefaultState, from(CERAMIC_WHITE)), "ceramic_stairs_white");
    public static final Block CERAMIC_ORANGE_STAIRS = registerBlock(new StairsBlock(CERAMIC_ORANGE::getDefaultState, from(CERAMIC_ORANGE)), "ceramic_stairs_orange");
    public static final Block CERAMIC_MAGENTA_STAIRS = registerBlock(new StairsBlock(CERAMIC_MAGENTA::getDefaultState, from(CERAMIC_MAGENTA)), "ceramic_stairs_magenta");
    public static final Block CERAMIC_LIGHT_BLUE_STAIRS = registerBlock(new StairsBlock(CERAMIC_LIGHT_BLUE::getDefaultState, from(CERAMIC_LIGHT_BLUE)), "ceramic_stairs_light_blue");
    public static final Block CERAMIC_YELLOW_STAIRS = registerBlock(new StairsBlock(CERAMIC_YELLOW::getDefaultState, from(CERAMIC_YELLOW)), "ceramic_stairs_yellow");
    public static final Block CERAMIC_LIME_STAIRS = registerBlock(new StairsBlock(CERAMIC_LIME::getDefaultState, from(CERAMIC_LIME)), "ceramic_stairs_lime");
    public static final Block CERAMIC_PINK_STAIRS = registerBlock(new StairsBlock(CERAMIC_PINK::getDefaultState, from(CERAMIC_PINK)), "ceramic_stairs_pink");
    public static final Block CERAMIC_GRAY_STAIRS = registerBlock(new StairsBlock(CERAMIC_GRAY::getDefaultState, from(CERAMIC_GRAY)), "ceramic_stairs_gray");
    public static final Block CERAMIC_LIGHT_GRAY_STAIRS = registerBlock(new StairsBlock(CERAMIC_LIGHT_GRAY::getDefaultState, from(CERAMIC_LIGHT_GRAY)), "ceramic_stairs_light_gray");
    public static final Block CERAMIC_CYAN_STAIRS = registerBlock(new StairsBlock(CERAMIC_CYAN::getDefaultState, from(CERAMIC_CYAN)), "ceramic_stairs_cyan");
    public static final Block CERAMIC_PURPLE_STAIRS = registerBlock(new StairsBlock(CERAMIC_PURPLE::getDefaultState, from(CERAMIC_PURPLE)), "ceramic_stairs_purple");
    public static final Block CERAMIC_BLUE_STAIRS = registerBlock(new StairsBlock(CERAMIC_BLUE::getDefaultState, from(CERAMIC_BLUE)), "ceramic_stairs_blue");
    public static final Block CERAMIC_BROWN_STAIRS = registerBlock(new StairsBlock(CERAMIC_BROWN::getDefaultState, from(CERAMIC_BROWN)), "ceramic_stairs_brown");
    public static final Block CERAMIC_GREEN_STAIRS = registerBlock(new StairsBlock(CERAMIC_GREEN::getDefaultState, from(CERAMIC_GREEN)), "ceramic_stairs_green");
    public static final Block CERAMIC_RED_STAIRS = registerBlock(new StairsBlock(CERAMIC_RED::getDefaultState, from(CERAMIC_RED)), "ceramic_stairs_red");
    public static final Block CERAMIC_BLACK_STAIRS = registerBlock(new StairsBlock(CERAMIC_BLACK::getDefaultState, from(CERAMIC_BLACK)), "ceramic_stairs_black");
    public static final WallBlock CERAMIC_WHITE_WALL = (WallBlock) registerBlock(new WallBlock(from(CERAMIC_WHITE)), "ceramic_wall_white");
    public static final WallBlock CERAMIC_ORANGE_WALL = (WallBlock) registerBlock(new WallBlock(from(CERAMIC_ORANGE)), "ceramic_wall_orange");
    public static final WallBlock CERAMIC_MAGENTA_WALL = (WallBlock) registerBlock(new WallBlock(from(CERAMIC_MAGENTA)), "ceramic_wall_magenta");
    public static final WallBlock CERAMIC_LIGHT_BLUE_WALL = (WallBlock) registerBlock(new WallBlock(from(CERAMIC_LIGHT_BLUE)), "ceramic_wall_light_blue");
    public static final WallBlock CERAMIC_YELLOW_WALL = (WallBlock) registerBlock(new WallBlock(from(CERAMIC_YELLOW)), "ceramic_wall_yellow");
    public static final WallBlock CERAMIC_LIME_WALL = (WallBlock) registerBlock(new WallBlock(from(CERAMIC_LIME)), "ceramic_wall_lime");
    public static final WallBlock CERAMIC_PINK_WALL = (WallBlock) registerBlock(new WallBlock(from(CERAMIC_PINK)), "ceramic_wall_pink");
    public static final WallBlock CERAMIC_GRAY_WALL = (WallBlock) registerBlock(new WallBlock(from(CERAMIC_GRAY)), "ceramic_wall_gray");
    public static final WallBlock CERAMIC_LIGHT_GRAY_WALL = (WallBlock) registerBlock(new WallBlock(from(CERAMIC_LIGHT_GRAY)), "ceramic_wall_light_gray");
    public static final WallBlock CERAMIC_CYAN_WALL = (WallBlock) registerBlock(new WallBlock(from(CERAMIC_CYAN)), "ceramic_wall_cyan");
    public static final WallBlock CERAMIC_PURPLE_WALL = (WallBlock) registerBlock(new WallBlock(from(CERAMIC_PURPLE)), "ceramic_wall_purple");
    public static final WallBlock CERAMIC_BLUE_WALL = (WallBlock) registerBlock(new WallBlock(from(CERAMIC_BLUE)), "ceramic_wall_blue");
    public static final WallBlock CERAMIC_BROWN_WALL = (WallBlock) registerBlock(new WallBlock(from(CERAMIC_BROWN)), "ceramic_wall_brown");
    public static final WallBlock CERAMIC_GREEN_WALL = (WallBlock) registerBlock(new WallBlock(from(CERAMIC_GREEN)), "ceramic_wall_green");
    public static final WallBlock CERAMIC_RED_WALL = (WallBlock) registerBlock(new WallBlock(from(CERAMIC_RED)), "ceramic_wall_red");
    public static final WallBlock CERAMIC_BLACK_WALL = (WallBlock) registerBlock(new WallBlock(from(CERAMIC_BLACK)), "ceramic_wall_black");
    //public static final Block RADIANT_BEACON = registerBlock(new RadiantBeaconBlock(), "radiant_beacon");
    //public static final Block RADIANT_BEACON_FRAMED = registerBlock(new FramedRadiantBeaconBlock(), null, "radiant_beacon_framed");
    public static final Block CRYSTAL_GLASS = registerBlock(new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid().setAllowsSpawn(AtumBlocks::neverAllowSpawn).setOpaque(AtumBlocks::isntSolid).setSuffocates(AtumBlocks::isntSolid).setBlocksVision(AtumBlocks::isntSolid)), "crystal_glass");
    public static final Block WHITE_STAINED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.WHITE), "white_stained_crystal_glass");
    public static final Block ORANGE_STAINED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.ORANGE), "orange_stained_crystal_glass");
    public static final Block MAGENTA_STAINED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.MAGENTA), "magenta_stained_crystal_glass");
    public static final Block LIGHT_BLUE_STAINED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.LIGHT_BLUE), "light_blue_stained_crystal_glass");
    public static final Block YELLOW_STAINED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.YELLOW), "yellow_stained_crystal_glass");
    public static final Block LIME_STAINED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.LIME), "lime_stained_crystal_glass");
    public static final Block PINK_STAINED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.PINK), "pink_stained_crystal_glass");
    public static final Block GRAY_STAINED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.GRAY), "gray_stained_crystal_glass");
    public static final Block LIGHT_GRAY_STAINED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.LIGHT_GRAY), "light_gray_stained_crystal_glass");
    public static final Block CYAN_STAINED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.CYAN), "cyan_stained_crystal_glass");
    public static final Block PURPLE_STAINED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.PURPLE), "purple_stained_crystal_glass");
    public static final Block BLUE_STAINED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.BLUE), "blue_stained_crystal_glass");
    public static final Block BROWN_STAINED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.BROWN), "brown_stained_crystal_glass");
    public static final Block GREEN_STAINED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.GREEN), "green_stained_crystal_glass");
    public static final Block RED_STAINED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.RED), "red_stained_crystal_glass");
    public static final Block BLACK_STAINED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.BLACK), "black_stained_crystal_glass");
    public static final Block CRYSTAL_GLASS_PANE = registerBlock(new AtumPaneBlock(), "crystal_glass_pane");
    public static final Block WHITE_STAINED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.WHITE, from(CRYSTAL_GLASS_PANE)), "white_stained_crystal_glass_pane");
    public static final Block ORANGE_STAINED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.ORANGE, from(CRYSTAL_GLASS_PANE)), "orange_stained_crystal_glass_pane");
    public static final Block MAGENTA_STAINED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.MAGENTA, from(CRYSTAL_GLASS_PANE)), "magenta_stained_crystal_glass_pane");
    public static final Block LIGHT_BLUE_STAINED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.LIGHT_BLUE, from(CRYSTAL_GLASS_PANE)), "light_blue_stained_crystal_glass_pane");
    public static final Block YELLOW_STAINED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.YELLOW, from(CRYSTAL_GLASS_PANE)), "yellow_stained_crystal_glass_pane");
    public static final Block LIME_STAINED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.LIME, from(CRYSTAL_GLASS_PANE)), "lime_stained_crystal_glass_pane");
    public static final Block PINK_STAINED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.PINK, from(CRYSTAL_GLASS_PANE)), "pink_stained_crystal_glass_pane");
    public static final Block GRAY_STAINED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.GRAY, from(CRYSTAL_GLASS_PANE)), "gray_stained_crystal_glass_pane");
    public static final Block LIGHT_GRAY_STAINED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.LIGHT_GRAY, from(CRYSTAL_GLASS_PANE)), "light_gray_stained_crystal_glass_pane");
    public static final Block CYAN_STAINED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.CYAN, from(CRYSTAL_GLASS_PANE)), "cyan_stained_crystal_glass_pane");
    public static final Block PURPLE_STAINED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.PURPLE, from(CRYSTAL_GLASS_PANE)), "purple_stained_crystal_glass_pane");
    public static final Block BLUE_STAINED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.BLUE, from(CRYSTAL_GLASS_PANE)), "blue_stained_crystal_glass_pane");
    public static final Block BROWN_STAINED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.BROWN, from(CRYSTAL_GLASS_PANE)), "brown_stained_crystal_glass_pane");
    public static final Block GREEN_STAINED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.GREEN, from(CRYSTAL_GLASS_PANE)), "green_stained_crystal_glass_pane");
    public static final Block RED_STAINED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.RED, from(CRYSTAL_GLASS_PANE)), "red_stained_crystal_glass_pane");
    public static final Block BLACK_STAINED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.BLACK, from(CRYSTAL_GLASS_PANE)), "black_stained_crystal_glass_pane");
    public static final Block PALM_FRAMED_CRYSTAL_GLASS = registerBlock(new GlassBlock(create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid()), "palm_framed_crystal_glass");
    public static final Block WHITE_STAINED_PALM_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.WHITE), "white_stained_palm_framed_crystal_glass");
    public static final Block ORANGE_STAINED_PALM_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.ORANGE), "orange_stained_palm_framed_crystal_glass");
    public static final Block MAGENTA_STAINED_PALM_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.MAGENTA), "magenta_stained_palm_framed_crystal_glass");
    public static final Block LIGHT_BLUE_STAINED_PALM_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.LIGHT_BLUE), "light_blue_stained_palm_framed_crystal_glass");
    public static final Block YELLOW_STAINED_PALM_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.YELLOW), "yellow_stained_palm_framed_crystal_glass");
    public static final Block LIME_STAINED_PALM_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.LIME), "lime_stained_palm_framed_crystal_glass");
    public static final Block PINK_STAINED_PALM_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.PINK), "pink_stained_palm_framed_crystal_glass");
    public static final Block GRAY_STAINED_PALM_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.GRAY), "gray_stained_palm_framed_crystal_glass");
    public static final Block LIGHT_GRAY_STAINED_PALM_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.LIGHT_GRAY), "light_gray_stained_palm_framed_crystal_glass");
    public static final Block CYAN_STAINED_PALM_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.CYAN), "cyan_stained_palm_framed_crystal_glass");
    public static final Block PURPLE_STAINED_PALM_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.PURPLE), "purple_stained_palm_framed_crystal_glass");
    public static final Block BLUE_STAINED_PALM_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.BLUE), "blue_stained_palm_framed_crystal_glass");
    public static final Block BROWN_STAINED_PALM_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.BROWN), "brown_stained_palm_framed_crystal_glass");
    public static final Block GREEN_STAINED_PALM_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.GREEN), "green_stained_palm_framed_crystal_glass");
    public static final Block RED_STAINED_PALM_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.RED), "red_stained_palm_framed_crystal_glass");
    public static final Block BLACK_STAINED_PALM_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.BLACK), "black_stained_palm_framed_crystal_glass");
    public static final Block DEADWOOD_FRAMED_CRYSTAL_GLASS = registerBlock(new GlassBlock(AbstractBlock.Properties.create(Material.GLASS).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid().setAllowsSpawn(AtumBlocks::neverAllowSpawn).setOpaque(AtumBlocks::isntSolid).setSuffocates(AtumBlocks::isntSolid).setBlocksVision(AtumBlocks::isntSolid)), "deadwood_framed_crystal_glass");
    public static final Block WHITE_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.WHITE), "white_stained_deadwood_framed_crystal_glass");
    public static final Block ORANGE_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.ORANGE), "orange_stained_deadwood_framed_crystal_glass");
    public static final Block MAGENTA_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.MAGENTA), "magenta_stained_deadwood_framed_crystal_glass");
    public static final Block LIGHT_BLUE_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.LIGHT_BLUE), "light_blue_stained_deadwood_framed_crystal_glass");
    public static final Block YELLOW_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.YELLOW), "yellow_stained_deadwood_framed_crystal_glass");
    public static final Block LIME_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.LIME), "lime_stained_deadwood_framed_crystal_glass");
    public static final Block PINK_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.PINK), "pink_stained_deadwood_framed_crystal_glass");
    public static final Block GRAY_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.GRAY), "gray_stained_deadwood_framed_crystal_glass");
    public static final Block LIGHT_GRAY_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.LIGHT_GRAY), "light_gray_stained_deadwood_framed_crystal_glass");
    public static final Block CYAN_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.CYAN), "cyan_stained_deadwood_framed_crystal_glass");
    public static final Block PURPLE_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.PURPLE), "purple_stained_deadwood_framed_crystal_glass");
    public static final Block BLUE_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.BLUE), "blue_stained_deadwood_framed_crystal_glass");
    public static final Block BROWN_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.BROWN), "brown_stained_deadwood_framed_crystal_glass");
    public static final Block GREEN_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.GREEN), "green_stained_deadwood_framed_crystal_glass");
    public static final Block RED_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.RED), "red_stained_deadwood_framed_crystal_glass");
    public static final Block BLACK_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS = registerBlock(createStainedGlassFromColor(DyeColor.BLACK), "black_stained_deadwood_framed_crystal_glass");
    public static final Block PALM_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new AtumPaneBlock(), "palm_framed_crystal_glass_pane");
    public static final Block WHITE_STAINED_PALM_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.WHITE, from(PALM_FRAMED_CRYSTAL_GLASS_PANE)), "white_stained_palm_framed_crystal_glass_pane");
    public static final Block ORANGE_STAINED_PALM_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.ORANGE, from(PALM_FRAMED_CRYSTAL_GLASS_PANE)), "orange_stained_palm_framed_crystal_glass_pane");
    public static final Block MAGENTA_STAINED_PALM_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.MAGENTA, from(PALM_FRAMED_CRYSTAL_GLASS_PANE)), "magenta_stained_palm_framed_crystal_glass_pane");
    public static final Block LIGHT_BLUE_STAINED_PALM_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.LIGHT_BLUE, from(PALM_FRAMED_CRYSTAL_GLASS_PANE)), "light_blue_stained_palm_framed_crystal_glass_pane");
    public static final Block YELLOW_STAINED_PALM_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.YELLOW, from(PALM_FRAMED_CRYSTAL_GLASS_PANE)), "yellow_stained_palm_framed_crystal_glass_pane");
    public static final Block LIME_STAINED_PALM_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.LIME, from(PALM_FRAMED_CRYSTAL_GLASS_PANE)), "lime_stained_palm_framed_crystal_glass_pane");
    public static final Block PINK_STAINED_PALM_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.PINK, from(PALM_FRAMED_CRYSTAL_GLASS_PANE)), "pink_stained_palm_framed_crystal_glass_pane");
    public static final Block GRAY_STAINED_PALM_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.GRAY, from(PALM_FRAMED_CRYSTAL_GLASS_PANE)), "gray_stained_palm_framed_crystal_glass_pane");
    public static final Block LIGHT_GRAY_STAINED_PALM_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.LIGHT_GRAY, from(PALM_FRAMED_CRYSTAL_GLASS_PANE)), "light_gray_stained_palm_framed_crystal_glass_pane");
    public static final Block CYAN_STAINED_PALM_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.CYAN, from(PALM_FRAMED_CRYSTAL_GLASS_PANE)), "cyan_stained_palm_framed_crystal_glass_pane");
    public static final Block PURPLE_STAINED_PALM_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.PURPLE, from(PALM_FRAMED_CRYSTAL_GLASS_PANE)), "purple_stained_palm_framed_crystal_glass_pane");
    public static final Block BLUE_STAINED_PALM_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.BLUE, from(PALM_FRAMED_CRYSTAL_GLASS_PANE)), "blue_stained_palm_framed_crystal_glass_pane");
    public static final Block BROWN_STAINED_PALM_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.BROWN, from(PALM_FRAMED_CRYSTAL_GLASS_PANE)), "brown_stained_palm_framed_crystal_glass_pane");
    public static final Block GREEN_STAINED_PALM_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.GREEN, from(PALM_FRAMED_CRYSTAL_GLASS_PANE)), "green_stained_palm_framed_crystal_glass_pane");
    public static final Block RED_STAINED_PALM_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.RED, from(PALM_FRAMED_CRYSTAL_GLASS_PANE)), "red_stained_palm_framed_crystal_glass_pane");
    public static final Block BLACK_STAINED_PALM_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.BLACK, from(PALM_FRAMED_CRYSTAL_GLASS_PANE)), "black_stained_palm_framed_crystal_glass_pane");
    public static final Block DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new AtumPaneBlock(), "deadwood_framed_crystal_glass_pane");
    public static final Block WHITE_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.WHITE, from(DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE)), "white_stained_deadwood_framed_crystal_glass_pane");
    public static final Block ORANGE_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.ORANGE, from(DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE)), "orange_stained_deadwood_framed_crystal_glass_pane");
    public static final Block MAGENTA_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.MAGENTA, from(DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE)), "magenta_stained_deadwood_framed_crystal_glass_pane");
    public static final Block LIGHT_BLUE_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.LIGHT_BLUE, from(DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE)), "light_blue_stained_deadwood_framed_crystal_glass_pane");
    public static final Block YELLOW_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.YELLOW, from(DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE)), "yellow_stained_deadwood_framed_crystal_glass_pane");
    public static final Block LIME_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.LIME, from(DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE)), "lime_stained_deadwood_framed_crystal_glass_pane");
    public static final Block PINK_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.PINK, from(DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE)), "pink_stained_deadwood_framed_crystal_glass_pane");
    public static final Block GRAY_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.GRAY, from(DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE)), "gray_stained_deadwood_framed_crystal_glass_pane");
    public static final Block LIGHT_GRAY_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.LIGHT_GRAY, from(DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE)), "light_gray_stained_deadwood_framed_crystal_glass_pane");
    public static final Block CYAN_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.CYAN, from(DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE)), "cyan_stained_deadwood_framed_crystal_glass_pane");
    public static final Block PURPLE_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.PURPLE, from(DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE)), "purple_stained_deadwood_framed_crystal_glass_pane");
    public static final Block BLUE_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.BLUE, from(DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE)), "blue_stained_deadwood_framed_crystal_glass_pane");
    public static final Block BROWN_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.BROWN, from(DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE)), "brown_stained_deadwood_framed_crystal_glass_pane");
    public static final Block GREEN_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.GREEN, from(DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE)), "green_stained_deadwood_framed_crystal_glass_pane");
    public static final Block RED_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.RED, from(DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE)), "red_stained_deadwood_framed_crystal_glass_pane");
    public static final Block BLACK_STAINED_DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE = registerBlock(new StainedGlassPaneBlock(DyeColor.BLACK, from(DEADWOOD_FRAMED_CRYSTAL_GLASS_PANE)), "black_stained_deadwood_framed_crystal_glass_pane");
    public static final Block LINEN_WHITE = registerBlock(new LinenBlock(DyeColor.WHITE), "linen_white");
    public static final Block LINEN_ORANGE = registerBlock(new LinenBlock(DyeColor.ORANGE), "linen_orange");
    public static final Block LINEN_MAGENTA = registerBlock(new LinenBlock(DyeColor.MAGENTA), "linen_magenta");
    public static final Block LINEN_LIGHT_BLUE = registerBlock(new LinenBlock(DyeColor.LIGHT_BLUE), "linen_light_blue");
    public static final Block LINEN_YELLOW = registerBlock(new LinenBlock(DyeColor.YELLOW), "linen_yellow");
    public static final Block LINEN_LIME = registerBlock(new LinenBlock(DyeColor.LIME), "linen_lime");
    public static final Block LINEN_PINK = registerBlock(new LinenBlock(DyeColor.PINK), "linen_pink");
    public static final Block LINEN_GRAY = registerBlock(new LinenBlock(DyeColor.GRAY), "linen_gray");
    public static final Block LINEN_LIGHT_GRAY = registerBlock(new LinenBlock(DyeColor.LIGHT_GRAY), "linen_light_gray");
    public static final Block LINEN_CYAN = registerBlock(new LinenBlock(DyeColor.CYAN), "linen_cyan");
    public static final Block LINEN_PURPLE = registerBlock(new LinenBlock(DyeColor.PURPLE), "linen_purple");
    public static final Block LINEN_BLUE = registerBlock(new LinenBlock(DyeColor.BLUE), "linen_blue");
    public static final Block LINEN_BROWN = registerBlock(new LinenBlock(DyeColor.BROWN), "linen_brown");
    public static final Block LINEN_GREEN = registerBlock(new LinenBlock(DyeColor.GREEN), "linen_green");
    public static final Block LINEN_RED = registerBlock(new LinenBlock(DyeColor.RED), "linen_red");
    public static final Block LINEN_BLACK = registerBlock(new LinenBlock(DyeColor.BLACK), "linen_black");
    public static final Block LINEN_CARPET_WHITE = registerBlock(new LinenCarpetBlock(DyeColor.WHITE), "linen_carpet_white");
    public static final Block LINEN_CARPET_ORANGE = registerBlock(new LinenCarpetBlock(DyeColor.ORANGE), "linen_carpet_orange");
    public static final Block LINEN_CARPET_MAGENTA = registerBlock(new LinenCarpetBlock(DyeColor.MAGENTA), "linen_carpet_magenta");
    public static final Block LINEN_CARPET_LIGHT_BLUE = registerBlock(new LinenCarpetBlock(DyeColor.LIGHT_BLUE), "linen_carpet_light_blue");
    public static final Block LINEN_CARPET_YELLOW = registerBlock(new LinenCarpetBlock(DyeColor.YELLOW), "linen_carpet_yellow");
    public static final Block LINEN_CARPET_LIME = registerBlock(new LinenCarpetBlock(DyeColor.LIME), "linen_carpet_lime");
    public static final Block LINEN_CARPET_PINK = registerBlock(new LinenCarpetBlock(DyeColor.PINK), "linen_carpet_pink");
    public static final Block LINEN_CARPET_GRAY = registerBlock(new LinenCarpetBlock(DyeColor.GRAY), "linen_carpet_gray");
    public static final Block LINEN_CARPET_LIGHT_GRAY = registerBlock(new LinenCarpetBlock(DyeColor.LIGHT_GRAY), "linen_carpet_light_gray");
    public static final Block LINEN_CARPET_CYAN = registerBlock(new LinenCarpetBlock(DyeColor.CYAN), "linen_carpet_cyan");
    public static final Block LINEN_CARPET_PURPLE = registerBlock(new LinenCarpetBlock(DyeColor.PURPLE), "linen_carpet_purple");
    public static final Block LINEN_CARPET_BLUE = registerBlock(new LinenCarpetBlock(DyeColor.BLUE), "linen_carpet_blue");
    public static final Block LINEN_CARPET_BROWN = registerBlock(new LinenCarpetBlock(DyeColor.BROWN), "linen_carpet_brown");
    public static final Block LINEN_CARPET_GREEN = registerBlock(new LinenCarpetBlock(DyeColor.GREEN), "linen_carpet_green");
    public static final Block LINEN_CARPET_RED = registerBlock(new LinenCarpetBlock(DyeColor.RED), "linen_carpet_red");
    public static final Block LINEN_CARPET_BLACK = registerBlock(new LinenCarpetBlock(DyeColor.BLACK), "linen_carpet_black");
    public static final Block PALM_PLANKS = registerBlock(new Block(create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD)), "palm_planks");
    public static final Block DEADWOOD_PLANKS = registerBlock(new Block(create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD)), "deadwood_planks");
    public static final Block PALM_LOG = registerBlock(new PalmLog(), "palm_log");
    public static final Block STRIPPED_PALM_LOG = registerBlock(new RotatedPillarBlock(from(PALM_LOG)), "stripped_palm_log");
    public static final Block PALM_WOOD = registerBlock(new RotatedPillarBlock(from(PALM_LOG)), "palm_wood");
    public static final Block STRIPPED_PALM_WOOD = registerBlock(new RotatedPillarBlock(from(PALM_LOG)), "stripped_palm_wood");
    public static final Block DEADWOOD_LOG = registerBlock(new DeadwoodLogBlock(), "deadwood_log");
    public static final Block STRIPPED_DEADWOOD_LOG = registerBlock(new DeadwoodLogBlock(), "stripped_deadwood_log");
    public static final Block DEADWOOD_WOOD = registerBlock(new DeadwoodLogBlock(), "deadwood_wood");
    public static final Block STRIPPED_DEADWOOD_WOOD = registerBlock(new DeadwoodLogBlock(), "stripped_deadwood_wood");
    public static final Block DEADWOOD_BRANCH = registerBlock(new DeadwoodBranchBlock(), null, "deadwood_branch");
    public static final Block PALM_STAIRS = registerBlock(new StairsBlock(PALM_PLANKS::getDefaultState, from(PALM_PLANKS)), "palm_stairs");
    public static final Block DEADWOOD_STAIRS = registerBlock(new StairsBlock(DEADWOOD_PLANKS::getDefaultState, from(DEADWOOD_PLANKS)), "deadwood_stairs");
    public static final Block PALM_SLAB = registerBlock(new SlabBlock(from(PALM_PLANKS)), "palm_slab");
    public static final Block DEADWOOD_SLAB = registerBlock(new SlabBlock(from(DEADWOOD_PLANKS)), "deadwood_slab");
    public static final Block PALM_SAPLING = registerBlock(new PalmSaplingBlock(), "palm_sapling");
    public static final Block POTTED_PALM_SAPLING = registerBaseBlock(new FlowerPotBlock(() -> (FlowerPotBlock) Blocks.FLOWER_POT.delegate.get(), () -> PALM_SAPLING, AbstractBlock.Properties.create(Material.MISCELLANEOUS).zeroHardnessAndResistance().notSolid()), "potted_palm_sapling");
    public static final Block PALM_LEAVES = registerBlock(new PalmLeavesBlock(), "palm_leaves");
    public static final Block DRY_LEAVES = registerBlock(new LeavesAtumBlock(), null, "dry_leaves");
    public static final Block PALM_CRATE = registerBlock(new CrateBlock(from(PALM_PLANKS)), "palm_crate");
    public static final Block DEADWOOD_CRATE = registerBlock(new CrateBlock(from(PALM_PLANKS)), "deadwood_crate");
    public static final Block PALM_LADDER = registerBlock(new AtumLadderBlock(), "palm_ladder");
    public static final Block DEADWOOD_LADDER = registerBlock(new AtumLadderBlock(), "deadwood_ladder");
    public static final Block PALM_FENCE = registerBlock(new FenceBlock(from(PALM_PLANKS)), "palm_fence");
    public static final Block DEADWOOD_FENCE = registerBlock(new FenceBlock(from(DEADWOOD_PLANKS)), "deadwood_fence");
    public static final Block PALM_FENCE_GATE = registerBlock(new FenceGateBlock(from(PALM_PLANKS)), "palm_fence_gate");
    public static final Block DEADWOOD_FENCE_GATE = registerBlock(new FenceGateBlock(from(DEADWOOD_PLANKS)), "deadwood_fence_gate");
    public static final Block PALM_HATCH = registerBlock(new AtumTrapDoorBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(3.0F).sound(SoundType.WOOD).notSolid().setAllowsSpawn(AtumBlocks::neverAllowSpawn)), "palm_hatch");
    public static final Block DEADWOOD_HATCH = registerBlock(new AtumTrapDoorBlock(Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(3.0F).sound(SoundType.WOOD).notSolid().setAllowsSpawn(AtumBlocks::neverAllowSpawn)), "deadwood_hatch");
    public static final Block PALM_DOOR = registerBlock(new DoorAtumBlock(from(PALM_PLANKS)), "palm_door");
    public static final Block DEADWOOD_DOOR = registerBlock(new DoorAtumBlock(from(DEADWOOD_PLANKS)), "deadwood_door");
    public static final Block LIMESTONE_BUTTON = registerBlock(new StoneButtonBlock(AbstractBlock.Properties.create(Material.MISCELLANEOUS).doesNotBlockMovement().hardnessAndResistance(0.5F)), "limestone_button");
    public static final Block PALM_BUTTON = registerBlock(new WoodButtonBlock(AbstractBlock.Properties.create(Material.MISCELLANEOUS).doesNotBlockMovement().hardnessAndResistance(0.5F).sound(SoundType.WOOD)), "palm_button");
    public static final Block DEADWOOD_BUTTON = registerBlock(new WoodButtonBlock(AbstractBlock.Properties.create(Material.MISCELLANEOUS).doesNotBlockMovement().hardnessAndResistance(0.5F).sound(SoundType.WOOD)), "deadwood_button");
    public static final Block LIMESTONE_PRESSURE_PLATE = registerBlock(new PressurePlateBlock(PressurePlateBlock.Sensitivity.MOBS, AbstractBlock.Properties.create(Material.ROCK).setRequiresTool().doesNotBlockMovement().hardnessAndResistance(0.5F)), "limestone_pressure_plate");
    public static final Block PALM_PRESSURE_PLATE = registerBlock(new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.create(Material.WOOD, PALM_PLANKS.getMaterialColor()).doesNotBlockMovement().hardnessAndResistance(0.5F).sound(SoundType.WOOD)), "palm_pressure_plate");
    public static final Block DEADWOOD_PRESSURE_PLATE = registerBlock(new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.create(Material.WOOD, DEADWOOD_PLANKS.getMaterialColor()).doesNotBlockMovement().hardnessAndResistance(0.5F).sound(SoundType.WOOD)), "deadwood_pressure_plate");
    public static final Block PALM_SIGN = registerSign(new AtumStandingSignBlock(AbstractBlock.Properties.create(Material.WOOD).doesNotBlockMovement().hardnessAndResistance(1.0F).sound(SoundType.WOOD), AtumWoodTypes.PALM), AtumWoodTypes.PALM);
    public static final Block DEADWOOD_SIGN = registerSign(new AtumStandingSignBlock(AbstractBlock.Properties.create(Material.WOOD).doesNotBlockMovement().hardnessAndResistance(1.0F).sound(SoundType.WOOD), AtumWoodTypes.DEADWOOD), AtumWoodTypes.DEADWOOD);
    public static final Block PALM_SCAFFOLDING = registerScaffolding(new AtumScaffoldingBlock(AbstractBlock.Properties.create(Material.MISCELLANEOUS, MaterialColor.SAND).doesNotBlockMovement().sound(SoundType.SCAFFOLDING).variableOpacity()), "palm_scaffolding");
    public static final Block DEADWOOD_SCAFFOLDING = registerScaffolding(new AtumScaffoldingBlock(AbstractBlock.Properties.create(Material.MISCELLANEOUS, MaterialColor.SAND).doesNotBlockMovement().sound(SoundType.SCAFFOLDING).variableOpacity()), "deadwood_scaffolding");
    public static final Block HEART_OF_RA = AtumItems.HEART_OF_RA;

    public static void setBlockInfo() {
        ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(PALM_SAPLING.getRegistryName(), () -> POTTED_PALM_SAPLING);
        //Fire Info
        FireBlock fire = (FireBlock) Blocks.FIRE;
        fire.setFireInfo(PALM_PLANKS, 5, 20);
        fire.setFireInfo(PALM_FENCE, 5, 20);
        fire.setFireInfo(PALM_FENCE_GATE, 5, 20);
        fire.setFireInfo(DEADWOOD_FENCE, 5, 20);
        fire.setFireInfo(DEADWOOD_FENCE_GATE, 5, 20);
        fire.setFireInfo(SHRUB, 60, 100);
        fire.setFireInfo(WEED, 60, 100);
        fire.setFireInfo(SPINNING_WHEEL, 2, 1);
        fire.setFireInfo(OPHIDIAN_TONGUE, 15, 100);
        fire.setFireInfo(PALM_PLANKS, 5, 20);
        fire.setFireInfo(DEADWOOD_PLANKS, 5, 20);
        fire.setFireInfo(PALM_LOG, 5, 5);
        fire.setFireInfo(DEADWOOD_LOG, 5, 5);
        fire.setFireInfo(PALM_SLAB, 5, 20);
        fire.setFireInfo(DEADWOOD_SLAB, 5, 20);
        fire.setFireInfo(PALM_LEAVES, 30, 60);
        fire.setFireInfo(DRY_LEAVES, 30, 60);
        fire.setFireInfo(DRY_GRASS, 60, 10);
        fire.setFireInfo(TALL_DRY_GRASS, 60, 10);
        fire.setFireInfo(PALM_STAIRS, 5, 20);
        fire.setFireInfo(DEADWOOD_STAIRS, 5, 20);
    }

    public static StainedGlassBlock createStainedGlassFromColor(DyeColor color) {
        return new StainedGlassBlock(color, AbstractBlock.Properties.create(Material.GLASS, color).hardnessAndResistance(0.3F).sound(SoundType.GLASS).notSolid().setAllowsSpawn(AtumBlocks::neverAllowSpawn).setOpaque(AtumBlocks::isntSolid).setSuffocates(AtumBlocks::isntSolid).setBlocksVision(AtumBlocks::isntSolid));
    }

    //Copied from vanilla Block class
    public static Boolean neverAllowSpawn(BlockState state, IBlockReader reader, BlockPos pos, EntityType<?> entity) {
        return false;
    }

    public static Boolean alwaysAllowSpawn(BlockState state, IBlockReader reader, BlockPos pos, EntityType<?> entity) {
        return true;
    }

    public static Boolean allowsSpawnOnLeaves(BlockState state, IBlockReader reader, BlockPos pos, EntityType<?> entity) {
        return entity == EntityType.OCELOT || entity == EntityType.PARROT;
    }

    public static boolean needsPostProcessing(BlockState state, IBlockReader reader, BlockPos pos) {
        return true;
    }

    public static boolean isntSolid(BlockState state, IBlockReader reader, BlockPos pos) {
        return false;
    }
}